import MLXRuntimeLMCommon
import MLXRuntimeTokenizers
import Foundation

/// Adapts `swift-transformers`'s `Tokenizers.AutoTokenizer` to
/// `MLXLMCommon.TokenizerLoader`/`MLXLMCommon.Tokenizer`, loading purely
/// from a local directory — never from the Hugging Face Hub.
///
/// This is a small local adapter, not a fork: `mlx-swift-lm`'s own
/// `MLXHuggingFace` package ships an equivalent bridge (generated by its
/// `#huggingFaceTokenizerLoader()` macro), but importing it would also pull
/// in `MLXHuggingFaceMacros`' compiler-plugin machinery and a Hub
/// downloader this app never uses (models are provisioned and verified by
/// `MLXModelVerifier` before load, never downloaded at generation time).
/// This adapter reproduces only the bridge itself.
///
/// `Tokenizers.AutoTokenizer.from(modelFolder:hubApi:strict:)` never
/// contacts the network for a local-folder load — its own documentation
/// states `hubApi` is unused in that path.
nonisolated struct SwiftTransformersTokenizerLoader: MLXRuntimeLMCommon.TokenizerLoader {
    func load(from directory: URL) async throws -> any MLXRuntimeLMCommon.Tokenizer {
        let upstream = try await MLXRuntimeTokenizers.AutoTokenizer.from(modelFolder: directory)
        return TokenizerBridge(upstream)
    }
}

/// Bridges one loaded `Tokenizers.Tokenizer` to `MLXLMCommon.Tokenizer`.
/// Field-for-field identical in shape to the macro-generated bridge in
/// `mlx-swift-lm`'s `MLXHuggingFaceMacros/HuggingFaceIntegrationMacros.swift`
/// at the pinned revision.
private struct TokenizerBridge: MLXRuntimeLMCommon.Tokenizer {
    private let upstream: any Tokenizers.Tokenizer

    init(_ upstream: any Tokenizers.Tokenizer) {
        self.upstream = upstream
    }

    func encode(text: String, addSpecialTokens: Bool) -> [Int] {
        upstream.encode(text: text, addSpecialTokens: addSpecialTokens)
    }

    // swift-transformers uses `decode(tokens:)` instead of `decode(tokenIds:)`.
    func decode(tokenIds: [Int], skipSpecialTokens: Bool) -> String {
        upstream.decode(tokens: tokenIds, skipSpecialTokens: skipSpecialTokens)
    }

    func convertTokenToId(_ token: String) -> Int? {
        upstream.convertTokenToId(token)
    }

    func convertIdToToken(_ id: Int) -> String? {
        upstream.convertIdToToken(id)
    }

    var bosToken: String? { upstream.bosToken }
    var eosToken: String? { upstream.eosToken }
    var unknownToken: String? { upstream.unknownToken }

    func applyChatTemplate(
        messages: [[String: any Sendable]],
        tools: [[String: any Sendable]]?,
        additionalContext: [String: any Sendable]?
    ) throws -> [Int] {
        do {
            return try upstream.applyChatTemplate(
                messages: messages, tools: tools, additionalContext: additionalContext)
        } catch Tokenizers.TokenizerError.missingChatTemplate {
            throw MLXRuntimeLMCommon.TokenizerError.missingChatTemplate
        }
    }
}
